export default{
     LOGIN_SUCCESS: 'LOGIN_SUCCESS',
     LOGIN_FAILED: 'LOGIN_FAILED',
     AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
     AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
     LOGOUT_USER: 'LOGOUT_USER'
}
